name: ditto_flutter_tools
description: "Diagnostic and Debugging Tools for Ditto in Flutter"
version: 1.0.0
homepage: "https://ditto.live"
repository: https://github.com/getditto/ditto_flutter_tools

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ditto_live: ^4.12.1
  webview_flutter: ^4.8.0
  path: ^1.9.0
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  timeago: ^3.7.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.32.12
  archive: ^3.6.1
  share_plus: ^10.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: live.ditto.ditto_flutter_tools
        pluginClass: DittoFlutterToolsPlugin
      ios:
        pluginClass: DittoFlutterToolsPlugin

  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/src/presence_assets/index.html
    - lib/src/presence_assets/main.js
    - lib/src/presence_assets/main.js.LICENSE.txt
    - lib/src/presence_assets/main.css
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
